id: PF7FB411F
initial_creation_type: input
source_metadata:
  Title: 'Citralakṣaṇam: an old text of Indian Art'
  Editor: Nagnajitacarya
  Publisher: The Asiatic Society
  Place of Publication: '-'
  Year: '1987'
  Citralakṣaṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:52:06.554280'
last_modified_at: '2022-03-08T16:52:06.554289'
